SCJM/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('',include('inventory.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    path('',include('order.urls')),
    path('',include('cashbox.urls')),
    path('',include('table.urls')),
    path('',include('customer.urls')),
    path('',include('supplier.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from .views import OrderSaveView, OrderView,preView
urlpatterns = [
    path('order/new/', OrderSaveView, name='order_save' ),
    path('order/table/', OrderView, name='products_waiter' ),
    path('order/preview/', preView, name= 'preview_order'),
    ]

order/models.py
from django.db import models
from shared.models import CommonModel
from inventory.models import Product
from table.models import Mesa
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver

class Pedido(models.Model):
    ESTADO_CHOICES = (
        (1, 'Pendiente'),
        (2, 'Entregado'),
        (3, 'Pagado'),
    )
    fecha_hora = models.DateTimeField("Fecha y Hora", auto_now_add=True)
    estado = models.CharField(max_length=20, choices=ESTADO_CHOICES)
    nro_mesa = models.ForeignKey(Mesa, on_delete=models.CASCADE, related_name="fkmesa")
    autor_usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    total_pedido = models.FloatField("Total pedido", default=0)

class ProductOrder(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    amount = models.IntegerField(default=1) 

@receiver(post_save, sender=Pedido)
def sumar_total_pedido(sender, instance, **kwargs):
    orderproducts = ProductOrder.objects.filter(order=instance)
    total = 0
    for orderproduct in orderproducts:
        producto = Product.objects.get(id=orderproduct.product_id)
        total += producto.price * orderproduct.amount
    instance.total_pedido = total
    post_save.disconnect(sumar_total_pedido, sender=Pedido)
    instance.save(update_fields=["total_pedido"])
    post_save.connect(sumar_total_pedido, sender=Pedido)

""" @receiver(pre_save, sender=Pedido)
def verificacion_estado_pedido(sender, instance, **kwargs):
    try:
        latest_order = Pedido.objects.filter(nro_mesa=instance.nro_mesa).latest('fecha_hora')
    except Pedido.DoesNotExist:
        latest_order = None

    if latest_order.estado == "3":
        raise ValueError("No se permite enviar más datos cuando el estado es 3.")
    else:
        return """

order/forms.py
from django import forms
from .models import Pedido,Mesa


class MesaForm(forms.ModelForm):
    class Meta:
        model = Mesa
        fields = ['nro_mesa']

    def __init__(self, *args, **kwargs) -> None:
        super(MesaForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})

class PedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['id','estado','nro_mesa']

    def __init__(self, *args, **kwargs) -> None:
        super(PedidoForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            if field=="nro_mesa":
                self.fields[field].widget.attrs.update({'class': 'form-control','display':'none'})
            self.fields[field].widget.attrs.update({'class': 'form-control'})       

order/views.py
import json
from pydantic import BaseModel
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from inventory.models import Product
from .models import Pedido, ProductOrder
from table.models import Mesa
from order.order import Order
from django.db import transaction

def access_mesero(view_func):
    def wrapper(request, *args, **kwargs):
        if not request.user.groups.filter(name='Meseros').exists():
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            return view_func(request, *args, **kwargs)
    return wrapper

@access_mesero
@login_required(login_url='/accounts/login/')
def OrderView(request):
    template_name = 'order/products_waiter.html'
    active_products = Product.objects.filter(is_active=True)
    try:
        latest_order = Pedido.objects.latest('fecha_hora')
    except Pedido.DoesNotExist:
        latest_order = None
    context = {
        'title': 'SCJM-Guardar Pedido',
        'all_products': active_products,
        'latest_order': latest_order,
    }
    return render(request, template_name, context)

class DataOrder(BaseModel):
    id: int
    price: float
    table_number: int

@login_required(login_url='/accounts/login/')
@csrf_exempt
@require_http_methods(["POST"])
@access_mesero
def OrderSaveView(request):
    data = json.loads(request.body.decode("utf-8"))
    data_products = data.get("products")
    data_table = data.get("table_number")
    mesa = Mesa.objects.get(nro_mesa=int(data_table))
    with transaction.atomic():
        order = Pedido.objects.create(nro_mesa=mesa)
        productos_asignados = []
        for product in data_products:
            data_order = DataOrder(id=product["Id"], price=product["price"], table_number=int(data_table))
            products = Product.objects.get(id=data_order.id)
            if products.stock >= product["cantidad"]:
                products.stock -= product["cantidad"]
                products.save()
                productos_asignados.append(products.id)
                productorder = ProductOrder.objects.create(product=products, order=order, amount=product["cantidad"])
                productorder.save()
            else:
                return JsonResponse({"success": False, "message": f"No hay suficiente stock para el producto: {products.name}"})
        order.estado = 1
        order.autor_usuario = request.user
        order.save()
        try:
            order_verify = Pedido.objects.get(id=order.id)
            success = order_verify is not None
            print(f"La orden {order.id} fue guardada correctamente: ", success)
        except Pedido.DoesNotExist:
            success = False
            print("La orden no se guardó correctamente.")
        return JsonResponse({"success": success})

@access_mesero
@login_required(login_url='/accounts/login/')
def preView(request):
    template_name='order/waiter.html'
    producto= Product.objects.all()
    return render(request, template_name, {'productos': producto})

def order_process(request, producto_id, method):
    order = Order(request)
    producto = Product.objects.get(id=producto_id)
    getattr(order, method)(producto)
    return redirect("order:products_waiter")

order/templates/order/products_waiter.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mesero</title>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@1,700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.10/dist/sweetalert2.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
    <style type="text/css">
        #body {
            text-align: center;
            background-color: black;
            width: 100%;
            height: 100%;
            color: white;
            font-family: 'Ubuntu', sans-serif;
        }

        #devolverse {
            width: 50%;
            height: 1%;
            color: white;
            background-color: #FCB13B;
            border: none;
            border-radius: 1rem;
            cursor: pointer;
        }

        #pedido {
            border-radius: 5rem;
            height: 3rem;
            width: 3rem;
        }

        #nav {
            display: flex;
            align-items: center;
            justify-content: space-around;
        }

        #comandar {
            border: none;
        }
    </style>
</head>

<body>
    <div id="body">
        <h1>System SJD</h1>
        <p>{{ request.user.email }}</p>
        <div id="nav">
            <a data-bs-toggle="modal" data-bs-target="#modal">
                <i class='bx bx-copy-alt' style="font-size: 4rem; cursor: pointer;"></i>
            </a>
        </div>
        <br>
        <a href="{% url 'preview_order' %}"><button id="devolverse"></button></a><br><br>
        <button type="submit" id="comandar">Comandar</button>
        <p>Total: $<span id="orderTotal">0</span></p>
        {% for product in all_products %}
        <div class="col-12">
            <div class="card" style="border-radius: 5rem;">
                <div class="card-body">
                    <img class="card-img-bottom" src="{{ product.img_route.url }}" style="width:7rem; height:7rem;">
                    <h5 class="card-title" style="color:black">{{ product.name }}</h5>
                    <p class="card-text" style="color: black">{{ product.description }}</p>
                    <p class="card-text" style="color:#85bb65">${{ product.price }}</p>
                    <i class='bx bx-minus' style="color:black"
                        onclick="removeFromCar({{ product.id }},{{ product.price }})"></i>
                    <span style="color: black;" id="contador-{{ product.id }}">0</span>
                    <i class='bx bx-plus' style="color:black"
                        onclick="addToCar({{ product.id }},{{ product.price }})"></i>
                </div>
            </div>
        </div><br>
        {% endfor %}
        <br><br>
        <div class="modal fade" id="modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content" style="color: black;">
                    <div class="modal-header">
                        <h3 class="modal-title">Detalle del pedido</h3>
                        <i class='bx bx-purchase-tag-alt' style="font-size:2.5rem; cursor:pointer;"></i>
                    </div>
                    <div class="modal-body">
                        {% if latest_order %}
                        <h5>Realizado por: {{ latest_order.autor_usuario.username }}</h5>
                        {% else %}
                        <h5>No hay pedidos disponibles</h5>
                        {% endif %}
                    </div>
                    {% if latest_order %}
                    <div class="modal-body" style="display:flex;flex-direction: column; align-items: flex-start;">
                        <ul>
                            <h5>Productos:</h5>
                            {% for product_order in latest_order.productorder_set.all %}
                            <li>{{ product_order.amount }} {{ product_order.product.name }}</li>
                            {% endfor %}
                            <b>Total: ${{ latest_order.total_pedido }}</b>
                        </ul>
                    </div>
                    {% endif %}
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.10/dist/sweetalert2.all.min.js"></script>
<script>
    const Toast = Swal.mixin({
        toast: true,
        position: 'top-end',
        showConfirmButton: false,
        timer: 3000,
        timerProgressBar: true,
    })

    const table_number = localStorage.getItem("table_number");
    window.addEventListener("load", (e) => {
        console.log(table_number);
        document.getElementById("devolverse").innerText = "Mesa " + table_number;
    });

    class Product {
        constructor(itemId, price, name, cantidad) {
            this.Id = itemId;
            this.price = price;
            this.name = name;
            this.cantidad = cantidad;
        }

        addContainer() {
            this.cantidad = this.cantidad + 1;
            document.getElementById('contador-' + this.Id).innerText = this.cantidad;
        }
    }

    class ShoppingCar {
        constructor() {
            this.products = [];
            this.total = 0;
        }

        addProduct(product) {
            this.products.push(product);
            this.total += product.price;
            this.updateOrderTotal();
        }

        removeProduct(product) {
            const index = this.products.indexOf(product);
            if (index > -1) {
                this.products.splice(index, 1);
                this.total -= product.price;
            }
            else {
                this.total = 0
            }
            this.updateOrderTotal();
        }

        updateOrderTotal() {
            const shoppingTotal = document.getElementById("orderTotal");
            shoppingTotal.innerText = this.total;
        }

        async sendDataOrder() {
            const data = {
                'table_number': table_number,
                'products': this.products
            };

            try {
                const response = await fetch("{% url 'order_save' %}", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify(data),
                });

                if (response.ok) {
                    const responseData = await response.json();
                    if (responseData.success == true) {
                        Toast.fire({
                            icon: 'success',
                            title: 'Pedido creado con éxito'
                        });
                    }
                    else {
                        Toast.fire({
                            icon: 'error',
                            title: responseData.message
                        });
                    }
                }
            } catch (error) {
                console.error('Error:', error);
                Toast.fire({
                    icon: 'error',
                    title: error
                });
            }
        }
    }

    const car = new ShoppingCar();

    let addToCar = (itemId, price) => {
        let existingProduct = car.products.find(product => product.Id === itemId);
        if (existingProduct) {
            existingProduct.addContainer();
            car.total += price;
        } else {
            let product = new Product(itemId, price, 'name', 0);
            product.addContainer();
            car.addProduct(product);
        }
        car.updateOrderTotal();
    };

    function removeFromCar(itemId, price) {
        let productIndex = -1;
        for (let i = 0; i < car.products.length; i++) {
            if (car.products[i].Id === itemId) {
                productIndex = i;
                break;
            }
        }

        if (productIndex !== -1) {
            const product = car.products[productIndex];
            if (product.cantidad > 1) {
                product.cantidad--;
                document.getElementById('contador-' + product.Id).innerText = product.cantidad;
            } else {
                car.products.splice(productIndex, 1);
                document.getElementById('contador-' + product.Id).innerText = '0';
            }
            car.total -= product.price;
            car.updateOrderTotal();
        }
    }
    const btnSendData = document.getElementById("comandar");
    btnSendData.addEventListener("click", (e) => {
        e.preventDefault();
        car.sendDataOrder();
    });

    setInterval(function () {
        fetch('/order/preview')
            .then(response => response.json())
            .then(data => {
                console.log(data);
            })
            .catch(error => {
                console.error('Error al realizar la consulta:', error);
            });
    }, 5000);
</script>

</html>

order/templates/order/waiter.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mesero</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@1,700&display=swap" rel="stylesheet">
    <style type="text/css">
        input {
            border: none;
            outline: none;
            border-radius: 0.5rem;
        }

        button {
            border: none;
            outline: none;
            border-radius: 0.5rem;
        }

        #imgs {
            display: flex;
            justify-content: space-around;
            align-items: center;
        }

        body {
            color: white;
            font-family: 'Ubuntu', sans-serif;
            background-color: black;
            width: 100%;
            height: 100%;
            text-align: center;
        }
    </style>
</head>

<body>
    <h1>System SJD</h1><br>
    <p>{{request.user.email}}</p><br>
    <div id="imgs">
        <img src="{% static 'img/avatars/dubai.jpg'%}" style="width: 20%;height: 20%; border-radius: 4rem;">
        <img src="{% static 'img/avatars/mulata.jpg'%}" style="width: 25%;height: 25%; border-radius: 4rem;">
    </div><br>
    <label for="">MESA: </label><br>
    <input type="number" placeholder="Ingrese el número de la mesa" id="nro_mesa">
    <a id="boton_mesa"><button >IR</button></a><br><br>
    <a href="{% url 'index' %}"><button class="btn btn-secondary mb-4">Volver</button></a>
    <h3>:D</h3>
</body>
<script>
    let boton_mesa = document.getElementById("boton_mesa");
    boton_mesa.addEventListener("click", (e) => {
        let input_mesa = document.getElementById("nro_mesa").value;
        if (input_mesa != null && input_mesa != "") {
            localStorage.setItem("table_number", input_mesa);
            window.location.href = '/order/table/';
        }
        else {
            alert("Primero tiene que ingresar un número de mesa")
        }
    });
</script>
</html>